from models.language_model import LanguageModel

languages = [
    {"name": "afrikaans", "acronym": "af"},
    {"name": "albanian", "acronym": "sq"},
    {"name": "amharic", "acronym": "am"},
    {"name": "arabic", "acronym": "ar"},
    {"name": "armenian", "acronym": "hy"},
    {"name": "assamese", "acronym": "as"},
    {"name": "aymara", "acronym": "ay"},
    {"name": "azerbaijani", "acronym": "az"},
    {"name": "bambara", "acronym": "bm"},
    {"name": "basque", "acronym": "eu"},
    {"name": "belarusian", "acronym": "be"},
    {"name": "bengali", "acronym": "bn"},
    {"name": "bhojpuri", "acronym": "bho"},
    {"name": "bosnian", "acronym": "bs"},
    {"name": "bulgarian", "acronym": "bg"},
    {"name": "catalan", "acronym": "ca"},
    {"name": "cebuano", "acronym": "ceb"},
    {"name": "chichewa", "acronym": "ny"},
    {"name": "chinese (simplified)", "acronym": "zh-CN"},
    {"name": "chinese (traditional)", "acronym": "zh-TW"},
    {"name": "corsican", "acronym": "co"},
    {"name": "croatian", "acronym": "hr"},
    {"name": "czech", "acronym": "cs"},
    {"name": "danish", "acronym": "da"},
    {"name": "dhivehi", "acronym": "dv"},
    {"name": "dogri", "acronym": "doi"},
    {"name": "dutch", "acronym": "nl"},
    {"name": "english", "acronym": "en"},
    {"name": "esperanto", "acronym": "eo"},
    {"name": "estonian", "acronym": "et"},
    {"name": "ewe", "acronym": "ee"},
    {"name": "filipino", "acronym": "tl"},
    {"name": "finnish", "acronym": "fi"},
    {"name": "french", "acronym": "fr"},
    {"name": "frisian", "acronym": "fy"},
    {"name": "galician", "acronym": "gl"},
    {"name": "georgian", "acronym": "ka"},
    {"name": "german", "acronym": "de"},
    {"name": "greek", "acronym": "el"},
    {"name": "guarani", "acronym": "gn"},
    {"name": "gujarati", "acronym": "gu"},
    {"name": "haitian creole", "acronym": "ht"},
    {"name": "hausa", "acronym": "ha"},
    {"name": "hawaiian", "acronym": "haw"},
    {"name": "hebrew", "acronym": "iw"},
    {"name": "hindi", "acronym": "hi"},
    {"name": "hmong", "acronym": "hmn"},
    {"name": "hungarian", "acronym": "hu"},
    {"name": "icelandic", "acronym": "is"},
    {"name": "igbo", "acronym": "ig"},
    {"name": "ilocano", "acronym": "ilo"},
    {"name": "indonesian", "acronym": "id"},
    {"name": "irish", "acronym": "ga"},
    {"name": "italian", "acronym": "it"},
    {"name": "japanese", "acronym": "ja"},
    {"name": "javanese", "acronym": "jw"},
    {"name": "kannada", "acronym": "kn"},
    {"name": "kazakh", "acronym": "kk"},
    {"name": "khmer", "acronym": "km"},
    {"name": "kinyarwanda", "acronym": "rw"},
    {"name": "konkani", "acronym": "gom"},
    {"name": "korean", "acronym": "ko"},
    {"name": "krio", "acronym": "kri"},
    {"name": "kurdish (kurmanji)", "acronym": "ku"},
    {"name": "kurdish (sorani)", "acronym": "ckb"},
    {"name": "kyrgyz", "acronym": "ky"},
    {"name": "lao", "acronym": "lo"},
    {"name": "latin", "acronym": "la"},
    {"name": "latvian", "acronym": "lv"},
    {"name": "lingala", "acronym": "ln"},
    {"name": "lithuanian", "acronym": "lt"},
    {"name": "luganda", "acronym": "lg"},
    {"name": "luxembourgish", "acronym": "lb"},
    {"name": "macedonian", "acronym": "mk"},
    {"name": "maithili", "acronym": "mai"},
    {"name": "malagasy", "acronym": "mg"},
    {"name": "malay", "acronym": "ms"},
    {"name": "malayalam", "acronym": "ml"},
    {"name": "maltese", "acronym": "mt"},
    {"name": "maori", "acronym": "mi"},
    {"name": "marathi", "acronym": "mr"},
    {"name": "meiteilon (manipuri)", "acronym": "mni-Mtei"},
    {"name": "mizo", "acronym": "lus"},
    {"name": "mongolian", "acronym": "mn"},
    {"name": "myanmar", "acronym": "my"},
    {"name": "nepali", "acronym": "ne"},
    {"name": "norwegian", "acronym": "no"},
    {"name": "odia (oriya)", "acronym": "or"},
    {"name": "oromo", "acronym": "om"},
    {"name": "pashto", "acronym": "ps"},
    {"name": "persian", "acronym": "fa"},
    {"name": "polish", "acronym": "pl"},
    {"name": "portuguese", "acronym": "pt"},
    {"name": "punjabi", "acronym": "pa"},
    {"name": "quechua", "acronym": "qu"},
    {"name": "romanian", "acronym": "ro"},
    {"name": "russian", "acronym": "ru"},
    {"name": "samoan", "acronym": "sm"},
    {"name": "sanskrit", "acronym": "sa"},
    {"name": "scots gaelic", "acronym": "gd"},
    {"name": "sepedi", "acronym": "nso"},
    {"name": "serbian", "acronym": "sr"},
    {"name": "sesotho", "acronym": "st"},
    {"name": "shona", "acronym": "sn"},
    {"name": "sindhi", "acronym": "sd"},
    {"name": "sinhala", "acronym": "si"},
    {"name": "slovak", "acronym": "sk"},
    {"name": "slovenian", "acronym": "sl"},
    {"name": "somali", "acronym": "so"},
    {"name": "spanish", "acronym": "es"},
    {"name": "sundanese", "acronym": "su"},
    {"name": "swahili", "acronym": "sw"},
    {"name": "swedish", "acronym": "sv"},
    {"name": "tajik", "acronym": "tg"},
    {"name": "tamil", "acronym": "ta"},
    {"name": "tatar", "acronym": "tt"},
    {"name": "telugu", "acronym": "te"},
    {"name": "thai", "acronym": "th"},
    {"name": "tigrinya", "acronym": "ti"},
    {"name": "tsonga", "acronym": "ts"},
    {"name": "turkish", "acronym": "tr"},
    {"name": "turkmen", "acronym": "tk"},
    {"name": "twi", "acronym": "ak"},
    {"name": "ukrainian", "acronym": "uk"},
    {"name": "urdu", "acronym": "ur"},
    {"name": "uyghur", "acronym": "ug"},
    {"name": "uzbek", "acronym": "uz"},
    {"name": "vietnamese", "acronym": "vi"},
    {"name": "welsh", "acronym": "cy"},
    {"name": "xhosa", "acronym": "xh"},
    {"name": "yiddish", "acronym": "yi"},
    {"name": "yoruba", "acronym": "yo"},
    {"name": "zulu", "acronym": "zu"},
]


def seed_language():
    LanguageModel.drop()

    print("Carregando os Idiomas")
    for language in languages:
        LanguageModel(language).save()
